#pragma once

#include "Namespace.hpp"

SPF_NS_BEGIN

namespace Keyboard
{
    enum class Key
    {
        Unknown,
        // Alphabet
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        // Numbers
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        // Numpad
        Numpad0,
        Numpad1,
        Numpad2,
        Numpad3,
        Numpad4,
        Numpad5,
        Numpad6,
        Numpad7,
        Numpad8,
        Numpad9,
        NumpadDivide,
        NumpadMultiply,
        NumpadSubtract,
        NumpadAdd,
        NumpadDecimal,
        NumpadEnter,
        // Function keys
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        // Arrows
        Left,
        Right,
        Up,
        Down,
        // Other
        Space,
        Enter,
        Escape,
        Tab,
        Backspace,
        Insert,
        Delete,
        Home,
        End,
        PageUp,
        PageDown,
        CapsLock,
        ScrollLock,
        NumLock,
        PrintScreen,
        Pause,
        // Modifiers
        LeftShift,
        RightShift,
        LeftControl,
        RightControl,
        LeftAlt,
        RightAlt,
        LeftSuper,
        RightSuper,
        Menu,
        // Punctuation
        Semicolon,
        Equal,
        Comma,
        Minus,
        Period,
        Slash,
        GraveAccent,
        LeftBracket,
        Backslash,
        RightBracket,
        Apostrophe,
        // Media keys
        MediaNextTrack,
        MediaPreviousTrack,
        MediaStop,
        MediaPlayPause,
        VolumeMute,
        VolumeDown,
        VolumeUp,
        // Browser keys
        BrowserBack,
        BrowserForward,
        BrowserRefresh,
        BrowserStop,
        BrowserSearch,
        BrowserFavorites,
        BrowserHome,
        // Application keys
        LaunchMail,
        LaunchMediaSelect,
        LaunchApp1,
        LaunchApp2,
        // OEM keys
        Oem1,
        OemPlus,
        OemComma,
        OemMinus,
        OemPeriod,
        Oem2,
        Oem3,
        Oem4,
        Oem5,
        Oem6,
        Oem7,
        Oem8,
        Oem102,
        // Special keys
        Sleep,
        // Mouse buttons (for consistency with KeyBinds)
        MouseLeft,
        MouseRight,
        MouseMiddle,
        MouseX1,
        MouseX2
    };
} // namespace Keyboard

SPF_NS_END
